name: Continuous Integration

on:
  push:
    branches:
     - master

jobs:
  build:
    runs-on: ubuntu-latest 
    steps:
      - name: Check out code
        uses: actions/checkout@v3 

      - name: Setup .NET 5
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '5.0.x'
      
      - name: Restore Dependencies
        run: dotnet restore .\src\AdvancedMicroservice.sln
      
      - name: Build App
        run: dotnet build .\src\AdvancedMicroservice.sln
